project:
  name: fraud360
  environment: dev

event_hubs:
  bootstrap_servers: ehns-fraud360.servicebus.windows.net:9093
  topic: fraud-transactions
  consumer_group: databricks-bronze-cg
  secret_scope: fraud360
  connection_secret_key: eventhubs-conn-string

storage:
  storage_account: stfraud360
  bronze_container: bronze
  silver_container: silver
  checkpoint_container: checkpoints

unity_catalog:
  catalog: fraud360
  bronze_schema: bronze
  silver_schema: silver

bronze:
  table_name: transactions_raw
  checkpoint_subpath: fraud360/bronze/transactions_raw
  trigger_interval: 10 seconds

silver:
  source_table: transactions_raw
  target_table: transactions_clean
  checkpoint_subpath: fraud360/silver/transactions_clean
  trigger_interval: 10 seconds
  watermark_delay: 10 minutes

snowflake:
  database: FRAUD360
  silver_schema: SILVER

  url_secret_key: snowflake-url
  user_secret_key: snowflake-user
  role_secret_key: snowflake-role
  warehouse_secret_key: snowflake-warehouse

  private_key_secret_key: snowflake-private-key
  private_key_passphrase_secret_key: snowflake-private-key-passphrase

silver_export:
  source_table: transactions_clean
  target_table: TRANSACTIONS_CLEAN

  checkpoint_subpath: fraud360/snowflake/transactions_clean

  trigger_interval: 30 seconds

  mode: append